# Generated by Django 4.1.3 on 2022-12-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='control.warehouse'),
            preserve_default=False,
        ),
    ]
