# Generated by Django 4.1.3 on 2022-12-04 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_remove_purchase_user_purchase_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='free_space',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='space',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
