# Generated by Django 4.1.3 on 2022-12-05 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_purchase_amount_alter_purchase_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.CharField(max_length=255)),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('delivery_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='control.warehouse')),
            ],
        ),
    ]
