# Generated by Django 4.1.3 on 2022-12-06 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0008_purchasearchive_shipmentarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasearchive',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archive_purchases', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentarchive',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archive_shipments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
